PassionPage_BaseApp/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "PassionPage Admin"
admin.site.index_title = "PassionPage Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PassionPage_Users.urls', namespace='PassionPage_Users')),
]

PassionPage_Users/urls.py
from django.urls import path
from .views import BaseView, HomePageView, LogoutPageView , LoginPageView, RegisterPageView, DetailPostView, CategoryListView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'PassionPage_Users'

urlpatterns = [
    path('', BaseView.as_view(), name='Base_Page'),
    path('Home/', HomePageView.as_view(), name='Home_Page'),
    path('Logout/', LogoutPageView.as_view(), name='Logout_Page'),
    path('Login/', LoginPageView.as_view(), name='Login_Page'),
    path('Register/', RegisterPageView.as_view(), name='Register_Page'),
    path('<slug:S_post>/', DetailPostView.as_view(), name='Single_Post_Page'),
    path('Category/<Category>/', CategoryListView.as_view(), name='Category_Page'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PassionPage_Users/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


def  User_Directory_Path(instance, filename):
    return 'media/Posts/{0}/{1}'.format(instance.id, filename)

class Category(models.Model):
    name = models.CharField(max_length=2000)

    def __str__(self):
        return self.name

# Making A form for post
class Post(models.Model):

    #for filtering out draft and published post that displays on the web
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(Status='published')
        
    #Status Option Data
    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    Title = models.CharField(max_length=250)
    First_Name = models.CharField(max_length=15)
    Last_Name = models.CharField(max_length=15)
    Email = models.EmailField(max_length=30)
    slug = models.SlugField(max_length=250, unique_for_date='Publish', default='default')
    Publish = models.DateTimeField(default=timezone.now )
    Author = models.ForeignKey (User, on_delete=models.CASCADE, related_name='blog_posts')
    Content = models.TextField()
    Category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    Category_Tag = models.CharField(max_length=20, default='Default')
    Image = models.ImageField(upload_to=User_Directory_Path)
    Status = models.CharField(max_length=10, choices=options, default='draft')
    Objects = models.Manager() #default Manager
    Newmanager = NewManager() #custom manager


    #to get to each individual post from a link
    def get_absolute_url(self):
        return reverse('PassionPage_Users:Single_Post_Page', args=[self.slug])
    
  
    #ordering the list of post from latest to least latest
    class Meta:
        ordering = ('-Publish',)[:8]

    #making Human Readable text on post title in the database
    def __str__(self):
        return self.Title
    

class Comment(models.Model):
    Post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='Comment' )
    Name = models.CharField(max_length=20)
    Email = models.EmailField(max_length=25)
    Comment = models.TextField(max_length=270)
    Publish = models.DateTimeField(default=timezone.now)
    Status = models.BooleanField(default=True)

    class Meta:
        ordering = ('-Publish',)

    def __str__(self):
        return f"Comment by {self.Name}"
    

PassionPage_Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import Comment
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password



class UserRegistrationForm(UserCreationForm):
   username = forms.CharField(
      widget= forms.TextInput(attrs = {'placeholder':'Enter Username'}),
      max_length = 30,
      required = True,
      label = 'Username' 
   )

   email = forms.EmailField(
      widget = forms.TextInput(attrs = {'placeholder': 'Enter Email'}),
      max_length = 30,
      required = True,
      label = 'Email'
   )

   password1 = forms.CharField(
      widget = forms.PasswordInput(attrs = {'placeholder': 'Enter Password', 'class':'Pwd password'}),
      max_length = 50,
      required = True,
      label = 'Passowrd',
   )

   password2 = forms.CharField(
      widget = forms.PasswordInput(attrs = {'placeholder': 'Confrim Password', 'class':'Pwd'}),
      max_length = 50,
      required = True,
      label = 'Confirm  Passowrd'
   )

   class Meta:
      model = User
      fields = ['username', 'email', 'password1', 'password2']
      exclude = ['help_text']

   def clean_username(self):
      username = self.cleaned_data['username']
      if User.objects.filter(username=username).exists():
         raise forms.ValidationError('Username is already Taken')
      return username
   
   def clean_email(self):
      email = self.cleaned_data['email']
      if User.objects.filter(email = email).exists():
         raise forms.ValidationError('Email is Already Taken')
      return email
   
   def clean(self):
      cleaned_data = super().clean()
      password1 = cleaned_data.get('password1')
      password2 = cleaned_data.get('password2')
      if password1 and password2 and password1 != password2:
         raise ValidationError('Passwords does not match')
      return cleaned_data
   
   def encryptPassword(self):
      password = make_password(self.cleaned_data['password1'])
      user = User.objects.create(
         username = self.cleaned_data['username'],
         email = self.cleaned_data['email'],
         password = password,
      )

      return user



class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control Pwd password', 'placeholder': 'Password'})
    )

    error_messages = {
        'invalid_login': 'Please enter a correct %(username)s and password. Note that both fields may be case-sensitive.',
        'inactive': 'This account is inactive.',
    }

class NewCommentForm(forms.ModelForm):
    Comment = forms.CharField(widget=forms.Textarea(attrs={'rows':8, 'cols':10 ,'placeholder':'What do you Think ?'}))

    class Meta:
        model = Comment
        fields = ['Comment']

PassionPage_Users/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserRegistrationForm, UserLoginForm, NewCommentForm
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.shortcuts import redirect, render
from django.contrib.auth import  login, logout
from django.contrib.auth.forms import AuthenticationForm
from .models import Post, Category
from django.views.generic import ListView, DetailView
from django.db.models import Count
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404


class BaseView(View):
     template_name = 'PassionPage_Users/Base.html'
     context_object_name = 'Updated_Post'
     
     def get_queryset(self):
        return Post.Newmanager.annotate(num_comments=Count('Comment')).order_by('-Publish')[:8]

     def get(self, request, *args, **kwargs):
        updated_posts = self.get_queryset()
        context = {
            self.context_object_name: updated_posts,
        }
        return render(request, self.template_name, context)

     
     
class HomePageView(LoginRequiredMixin, ListView):
     template_name = 'PassionPage_Users/Home.html'
     context_object_name = 'Updated_Post'
     
     def get_queryset(self):
        updated_posts = Post.Newmanager.annotate(num_comments=Count('Comment')).order_by('-Publish')[:8]
        return updated_posts

     def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        older_posts = None
        updated_posts = self.get_queryset()

        if len(updated_posts):
            older_posts = Post.Newmanager.annotate(num_comments=Count('Comment')).order_by('Publish')[:8]

        context['Older_Post'] = older_posts
        return context


class LogoutPageView(View):
     template_name = 'PassionPage_Users/Login.html'

     def get(self, request):
           logout(request)
           messages.warning(request,'you have successfully logged out' )
           return redirect('PassionPage_Users:Login_Page') 

     
class LoginPageView(View):
     template_name = 'PassionPage_Users/Login.html'

     def get(self, request):
        form = UserLoginForm()
        return render(request, self.template_name, {'form': form})

     def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                messages.success(request, f'Hello {user.username}, You successfully Logged in')
                return redirect('PassionPage_Users:Home_Page')
            else:
                messages.error(request, 'Invalid Username or Password.')
        else:
            messages.error(request, 'The Credentials you entered are incorrect')
        return render(request, self.template_name, {'form': form})
     
     
class RegisterPageView(View):
     template_name = 'PassionPage_Users/Register.html'

     def get(self, request):
          form = UserRegistrationForm()
          return render(request, self.template_name, {'form': form})

     def post(self, request):
          form = UserRegistrationForm(request.POST)
          if form.is_valid():
               form.save()
               username = form.cleaned_data.get('username')
               messages.success(request, mark_safe(f'Account for {username} was  successfully created!'))
               return redirect('PassionPage_Users:Login_Page')
          return render(request, self.template_name, {'form': form})
     

class DetailPostView(LoginRequiredMixin ,FormMixin, DetailView):
    model = Post,
    template_name = 'PassionPage_Users/Detail.html'
    form_class = NewCommentForm
    slug_field = 'slug'
    slug_url_kwarg = 'S_post'

    
    def get_queryset(self):
        # Retrieve the queryset for the detail view
        return Post.Objects.all()  


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        S_post = self.get_object()
        comment = S_post.Comment.filter(Status=True)
        context['Comment'] = comment
        if self.request.user.is_authenticated:
            context['user_comment'] = None
            context['comment_form'] = self.get_form()
        else:
            context['user_comment'] = None
            context['comment_form'] = None

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            user_comment = form.save(commit=False)
            user_comment.Name = self.request.user.username
            user_comment.Email = self.request.user.email
            user_comment.Post = self.object
            user_comment.save()
            messages.success(request, 'Your Comment was successfully added')
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
        

class CategoryListView(LoginRequiredMixin,  ListView):
    template_name = 'PassionPage_Users/Category.html'
    context_object_name = 'Category_Posts'
    queryset = Post.Objects.filter(Status='published')

    def get_queryset(self):
        category_name = self.kwargs['Category']
        category = get_object_or_404(Category, name=category_name)
        category_posts = self.queryset.filter(Category=category)
        return category_posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_name = self.kwargs['Category']
        context['Category'] = category_name
        return context

templates/PassionPage_Users/Base.html
{% include  'PassionPage_Users/Navigation.html' %}
    {% load static %}
    {% block content %}

    <div class="User_Base">

        <div class="Data_Wrapper">  

            <div class="Welcome_Message wel_msg">
                <h3>Welcome to Passion Pages</h3>
                <p>Connecting You to the World's Stage, Experience the Pulse!</p>
            </div>

            <div class="Inner_Message wel_msg">
                <h3>Explore Your Passions with Passion Pages</h3>
                <p>
                    Delve into a vibrant realm of unique experiences through Passion Pages. Engage, discover, and connect with a diverse tapestry of passions tailored to your interests. Embrace your desires, explore uncharted territories, and join a community that celebrates what fuels your soul. Ignite your curiosity and indulge in an array of captivating experiences—all here at Passion Pages.
                </p>
                <div class="cta_Button">
                    <button> <a href="{% url 'PassionPage_Users:Login_Page' %}"> Get Started Now</a> </button>
                </div>
            </div>

            <h3>Latest Posts</h3>

            <div class="Data_Grid_Wrapper">
                {% for Blog_Post in Updated_Post %}
                    <div class="Data_Grid_Info">
                    <img src="{{Blog_Post.Image.url}}" alt="{{Blog_Post.Category_Tag}}">
        
                        <div class="Meta_Data">
                            
                        <a href="{{Blog_Post.get_absolute_url}}">{{ Blog_Post.Title|truncatechars:38}}</a>
        
                        <div class="Data_Grid_Meta_Info Flex">
                            <div class="Meta_Info">
                                <h3>By {{Blog_Post.Last_Name}}</h3>
                            </div>
                            <div class="Meta_Info">
                                <h3>{{Blog_Post.Category_Tag}}</h3>
                            </div>
                        </div>
        
                        <div class="Data_Grid_Social Flex">
                            <div class="Socials S_Flex">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chat-left-fill Ua_Comment" viewBox="0 0 16 16">
                                    <path d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                                  </svg>
                                <h3>{{Blog_Post.num_comments}}</h3>
                            </div>
                        </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
        
            
            <div class="Feature wel_msg">
                <h3>Feature</h3>
                <p>Passion Pages: A vivid tapestry of human zeal and diverse narratives. Explore and celebrate passions through captivating stories, connecting enthusiasts on an exhilarating journey of creativity and discovery.</p>
            </div>
        </div>
    </div>
 
    {% endblock %}
{% include  'PassionPage_Users/Footer.html' %}

templates/PassionPage_Users/Category.html
{% include  'PassionPage_Users/Navigation.html' %}
    {% load static %}
    {% block content %}

    <div class="User" id="Authenticated">
        <div class="User_Auth">
            <h3>Welcome back, {{user.username}}</h3>
            <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-person-fill User_Activator2" viewBox="0 0 16 16">
                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
              </svg>

            <div class="User_Verified2  User_Revealer2">
                <ul>
                {% if user.is_authenticated %} 
                    <li><a href="{% url 'PassionPage_Users:Logout_Page' %}">Logout</a></li>
                {% endif %}
                </ul>
            </div>

            
        </div>

    
        {% if Category_Posts %}
        <div class="Updates">
            <h1>{{ Category }} Related Posts</h1>
        </div> 
        {% endif %}

        <div class="Data_Grid_Wrapper">
        {% for Categories_Post in Category_Posts %}
            <div class="Data_Grid_Info">
            <img src="{{Categories_Post.Image.url}}" alt="{{Categories_Post.Category_Tag}}">

                <div class="Meta_Data">
                    
                <a href="{{Categories_Post.get_absolute_url}}">{{ Categories_Post.Title|truncatechars:42}}</a>

                <div class="Data_Grid_Meta_Info Flex">
                    <div class="Meta_Info">
                        <h3>By {{Categories_Post.Last_Name}}</h3>
                    </div>
                    <div class="Meta_Info">
                        <h3>{{Categories_Post.Category_Tag}}</h3>
                    </div>
                </div>

                <div class="Data_Grid_Social Flex">
                    <div class="Socials S_Flex">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chat-left-fill Ua_Comment" viewBox="0 0 16 16">
                            <path d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                          </svg>
                        <h3>{{Categories_Post.num_comments}}</h3>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
        </div>




    </div>


    
 

    {% endblock %}
    {% include  'PassionPage_Users/Footer.html' %}

templates/PassionPage_Users/Detail.html
{% include  'PassionPage_Users/Navigation.html' %}
    {% load static %}
    {% block content %}

    <div class="User" id="Authenticated">
        <div class="User_Auth">

        <lord-icon
            src="https://cdn.lordicon.com/ezsjqygj.json"
            trigger="loop"
            delay="1000"
            colors="primary:#000000,secondary:#000000"
            style="width:50px;height:40px">
        </lord-icon>

            <h3>Welcome back, {{user.username}}</h3>
            <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-person-fill User_Activator2" viewBox="0 0 16 16">
                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
              </svg>

            <div class="User_Verified2  User_Revealer2">
                <ul>
                {% if user.is_authenticated %} 
                    <li><a href="{% url 'PassionPage_Users:Logout_Page' %}">Logout</a></li>
                {% endif %}
                </ul>
            </div>

            
        </div>

        {% if messages %}
        {% for message in messages %}
                {% if message.tags == 'success' %} 
                    <div class="SuccessMessages  Msg">
                        <p>{{ message }}</p>
                    </div> 
                {% endif %}
        {% endfor %}
    {% endif %} 

            <div class="Main_Post_Wrapper">
                <div class="Main_Post_Details">
                    <div class="Main_Post_Details_Header">
                        <h1>{{object.First_Name}} {{object.Last_Name}}</h1>
                        <h1>{{object.Publish}}</h1>
                    </div>
            
                    <img  class="Main_Post_Details_Image" src="{{object.Image.url}}" alt="{{object.Category_Tag}}">
            
                    <div class="Main_Post_Details_Content">
                        <h1>{{object.Title}}</h1>
                        <p>{{object.Content}}</p>
                    </div>
            
                    <div class="Main_Post_Details_Meta_Info">
                        <hr class="hr">

                        <div class="Reactions">
                            
                            <div class="Comment_Reaction">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chat-left-fill Ua_Comment" viewBox="0 0 16 16">
                                    <path d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                                  </svg>
                                {% with Comment.count as total_comments %}
                                    <p>{{total_comments}} Comment</p>
                                {% endwith %}
                            </div>
                    
                            <a href="{% url 'PassionPage_Users:Home_Page' %}">Back</a>
                    
                        </div>  
                    </div>
    
                </div>

                <div class="Comment_Box">      
                    <h1>Make a new comment</h1>

                    <form action="#" method="post"> 
                        {% csrf_token %}
                        {{comment_form.Comment}}
                        <button class="btn" type="submit">submit</button>
                    </form>
                       
                </div>

                {% if Comment %}
                <div class="Comment_Posted">
                    <h1>Latest Comments</h1>
                    {% for UserComment in Comment %}
                            <div class="Comment_Wrapper">     
                                <div class="Comment_Posted_Info">
                                    <h3>{{UserComment.Name}}</h3>
                                    <h3>{{UserComment.Publish}}</h3>
                            </div>
                            <p>{{UserComment.Comment|truncatechars:270}}</p>
                            </div>
                       
                    {% endfor %}
                </div>
                {% else %}
                    <div class="No_Comment_Available">
                        <p>No comments available</p>
                    </div>
                {% endif %}
            </div>



    </div>


    
 

    {% endblock %}
    {% include  'PassionPage_Users/Footer.html' %}

templates/PassionPage_Users/Login.html
{% include  'PassionPage_Users/Navigation.html' %}
    {% load static %}
    {% block content %}

    <div class="User">

        {% if messages %}
                {% for message in messages %}
                        {% if message.tags == 'success' %} 
                            <div class="SuccessMessages  Msg">
                                <p>{{ message }}</p>
                            </div> 
                         {% endif %}
                {% endfor %}
        {% endif %} 

        {% if messages %}
                {% for message in messages %}
                        {% if message.tags == 'warning' %} 
                            <div class="WarningMessages  Msg">
                                <p>{{ message }}</p>
                            </div> 
                         {% endif %}
                {% endfor %}
        {% endif %} 

        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="ErrorMessages Msg ">
                    <p>{{ message }}</p>
                </div> 
            {% endif %}
        {% endfor %}
     {% endif %}
    

        <div class="Form_Wrapper">

            <h1>Login </h1>
            <form action="." method="POST" class="SubmitListener">  

              {% csrf_token %}
              {{form.username}}
              {{form.email}}
              <div class="pwd_flex Focus">
                {{form.password}}
                <button class="Show_Password password-toggle-button"  type="button"><i  class="fa fa fa-eye"></i></button>
              </div>
            

            <button class="btn" type="submit">Explore</button>
                    
          
                   <div class="Form-bottom">
        
                      <div class="form-links flex">
                        <p>Don't  have an account?</p> &nbsp;
                        <a href="{% url 'PassionPage_Users:Register_Page' %}">Register</a>
                      </div>
                    
                   </div>
            </form>
        
           
        
          </div>
    </div>
 

    
    <script>
        // Logic to remove Errors
          let Close = document.querySelectorAll('.Close')
          let disappear = document.querySelectorAll('.Disappear')
  
          Close.forEach((closeBtn, index) => {
                  closeBtn.addEventListener('click', () => {
                  disappear[index].classList.toggle('remove');
              })
          })


          // Script to reveal and hide user authentication 
    document.addEventListener('DOMContentLoaded', function(){
        let activator2 = document.querySelector('.User_Activator2')
        let revealer2 =  document.querySelector('.User_Revealer2')

        activator2.addEventListener('click', function(){
            revealer2.classList.toggle('Activate')
                Reveal_NavList.classList.remove('Activate')
            })

})

      </script>

    {% endblock %}
{% include  'PassionPage_Users/Footer.html' %}

templates/PassionPage_Users/Navigation.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <meta charset="utf-8">
    <title>PassionPages</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'PassionPage_Users/css/Base.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.lordicon.com/lordicon.js"></script>
</head>

<body>

{% block content %}

     <div class="Wrapper">
        <nav>
            <div class="Logo">
                <img src="{% static 'PassionPage_Users/images/Logo_1.png' %}" alt="Logo">

                <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-list Navlist_Listener" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                  </svg>
            </div>


            <!-- <ul class="Auth_Wrap Wrap "> 
                       
                </li>

            </ul>
   -->

        </nav>

        <div class="Navigation Reveal_NavList">
                <ul class="List_Wrap Wrap Mobile">

                    <li>
                        <a href="{% url 'PassionPage_Users:Home_Page' %}">Home</a>
                    </li>
    
                    <li>
                        <a href="#">Bookmark</a>
                    </li>
    
                    <li class="Nav_Parent">
                        <a href="#">Category</a>
                        <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                            <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                          </svg>
                          
                        <ul class="Nav_Child Child_Links">
                        {% for Category_List_Item in Category_List_Options %}
                            <li><a href="/Category/{{Category_List_Item.name}}">{{Category_List_Item.name}}</a></li>
                        {% endfor %}
                        </ul>

                    </li>
    
                    <li>
                        <a href="#">Terms</a>
                    </li>
    
                    <li>
                        <a href="#">Privacy</a>
                    </li>
    
                    <li>
                        <a href="#">About</a>
                    </li>
    
                    <li class="Nav_Parent2">
                        <a href="#">Settings</a>
                        <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                            <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                          </svg>
                        <ul class="Nav_Child2 Child_Links">
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Edit Profile</a></li>
                            <li><a href="#">Change Password</a></li>
                            <li><a href="#">Delete Account</a></li>
                            
                        </ul>
                    </li>
                
    
                </ul>
        </div>

        <div class="User">

            <div class="User_Auth  ">
                <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-person-fill User_Activator" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                  </svg>
    
                <div class="User_Verified User_Revealer">
                    <ul>
                        <li><a href="{% url 'PassionPage_Users:Login_Page' %}">Log in</a></li>
                        <li><a href="{% url 'PassionPage_Users:Register_Page' %}">Register</a></li>
                    </ul>
                </div>
    
                
            </div>
    
        </div>
     

     </div>

    <!-- Java Script
    ================================================== -->
    <script src="{% static '/PassionPage_Users/js/Base.js' %}"></script>

<script>
        
// Script to reveal and hide user authentication 
document.addEventListener('DOMContentLoaded', function(){
let activator = document.querySelector('.User_Activator')
let revealer =  document.querySelector('.User_Revealer')


activator.addEventListener('click', function(){
    revealer.classList.toggle('Activate')
        Reveal_NavList.classList.remove('Activate')
    })


})
        
</script>

{% endblock %}
</body>